const { AzureOpenAI } = require('openai');

// Mock responses for testing without API keys
const getMockCouncilResponse = (question, members) => {
  const mockMembers = members.map((member, index) => ({
    id: member.id,
    name: member.name,
    provider: member.provider,
    color: member.color,
    summary: `Mock response from ${member.name}: This is a simulated analysis for "${question.substring(0, 50)}...".`,
    reasoning: `## Analysis by ${member.name}\n\n- **Key Point 1**: Simulated insight from Azure OpenAI\n- **Key Point 2**: Mock reasoning for demonstration\n- **Conclusion**: This is a test response in mock mode.\n\n*Generated by: ${member.provider}*`,
    confidence: 75 + (index * 5)
  }));

  return {
    question,
    members: mockMembers,
    chairman: {
      finalDecision: `## Chairman's Decision\n\nAfter reviewing all council member responses, here's the synthesized recommendation:\n\n**Consensus Points:**\n- All members agree this is a mock demonstration\n- Azure migration is proceeding successfully\n- Frontend deployment is working correctly\n\n**Final Recommendation:**\nThis mock response demonstrates that the Azure Static Web Apps deployment is functioning properly. The council framework is ready for real AI integration once Azure OpenAI credentials are configured.\n\n*Chairman Model: GPT-5.1 (Mock Mode)*`,
      consensusScore: 85,
      keyAgreements: ['Mock demonstration working', 'Azure deployment successful', 'Frontend integration complete'],
      keyDisagreements: ['No real disagreements in mock mode']
    }
  };
};

const getModelColor = (modelId) => {
  const colorMap = {
    'gpt-4.1': '#F97316',
    'o4-mini': '#A855F7', 
    'grok-4-fast-reasoning': '#06B6D4',
    'gpt-4o': '#EC4899',
    'o3': '#14B8A6'
  };
  return colorMap[modelId] || '#6B7280';
};

const getOpenAIClient = () => {
  const apiKey = process.env.AZURE_OPENAI_API_KEY;
  const endpoint = process.env.AZURE_OPENAI_ENDPOINT;

  if (!apiKey || !endpoint) {
    return null;
  }

  // Use AzureOpenAI client for Azure OpenAI Service
  return new AzureOpenAI({
    apiKey,
    endpoint: endpoint.replace(/\/$/, ''), // Remove trailing slash if present
    apiVersion: '2024-12-01-preview'
  });
};

module.exports = async function (context, req) {
  context.log('Council endpoint called');

  // Check if we should use mock mode or real Azure OpenAI
  const useMock = process.env.USE_MOCK === 'true';
  const hasApiKeys = !!(process.env.AZURE_OPENAI_API_KEY && process.env.AZURE_OPENAI_ENDPOINT);
  const shouldUseMock = useMock || !hasApiKeys;
  
  context.log('Council API - useMock:', useMock, 'hasApiKeys:', hasApiKeys, 'shouldUseMock:', shouldUseMock);
  
  const { question, selectedMembers = ['gpt-4.1', 'o4-mini', 'grok-4-fast-reasoning'], chairmanModel = 'gpt-4.1' } = req.body || {};

  if (!question) {
    context.res = {
      status: 400,
      body: { error: 'Question is required' }
    };
    return;
  }

  try {
    // Always use mock mode for now since we don't have API keys configured
    if (shouldUseMock) {
      const mockMembers = selectedMembers.map(id => ({
        id,
        name: id.toUpperCase(),
        provider: 'Azure OpenAI',
        color: getModelColor(id)
      }));

      const mockResponse = getMockCouncilResponse(question, mockMembers);
      
      context.res = {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type'
        },
        body: {
          success: true,
          mode: 'mock',
          question,
          data: mockResponse
        }
      };
      return;
    }

    // Real Azure OpenAI implementation
    const client = getOpenAIClient();
    const members = [];
    
    // Helper to determine if model uses max_completion_tokens (o-series models)
    const usesCompletionTokens = (model) => model.startsWith('o');
    
    // Helper to detect xAI models (like grok)
    const isXaiModel = (model) => model.includes('grok');
    
    // Helper for model-specific timeout (xAI/grok models need much longer timeouts)
    const getModelTimeout = (model) => isXaiModel(model) ? 120000 : 30000;
    
    // Call each council member (model) in parallel
    const memberPromises = selectedMembers.map(async (modelId) => {
      try {
        const requestParams = {
          model: modelId,
          messages: [
            {
              role: 'system',
              content: `You are ${modelId}, a council member providing expert analysis. Give a structured, insightful response focusing on your unique perspective. Be concise but thorough.`
            },
            {
              role: 'user', 
              content: question
            }
          ],
          temperature: usesCompletionTokens(modelId) ? 1 : 0.7 // o-series models require temperature=1
        };
        
        // Use correct token parameter based on model type
        if (usesCompletionTokens(modelId)) {
          requestParams.max_completion_tokens = 500;
        } else {
          requestParams.max_tokens = 500;
        }
        
        // Add timeout for the request
        const timeoutMs = getModelTimeout(modelId);
        const timeoutPromise = new Promise((_, reject) => 
          setTimeout(() => reject(new Error(`Request timed out after ${timeoutMs/1000}s`)), timeoutMs)
        );
        
        const completion = await Promise.race([
          client.chat.completions.create(requestParams),
          timeoutPromise
        ]);
        
        // Extract content - handle different response formats
        let content = null;
        if (completion.choices && completion.choices[0]) {
          const choice = completion.choices[0];
          content = choice.message?.content || choice.text || null;
        }
        
        context.log(`Model ${modelId} response:`, content ? `${content.substring(0, 100)}...` : 'No content');

        return {
          id: modelId,
          name: modelId.toUpperCase(),
          provider: isXaiModel(modelId) ? 'xAI via Azure' : 'Azure OpenAI',
          color: getModelColor(modelId),
          summary: content || `No response content from ${modelId}`
        };
      } catch (error) {
        context.log('Error calling model', modelId, error);
        const isTimeout = error.message?.includes('timed out');
        const errorMessage = isTimeout 
          ? `Model ${modelId} timed out. This model may be slow or overloaded. Try again later.`
          : `Error: Unable to get response from ${modelId}. ${error.message}`;
        return {
          id: modelId,
          name: modelId.toUpperCase(),
          provider: isXaiModel(modelId) ? 'xAI via Azure' : 'Azure OpenAI',
          color: getModelColor(modelId),
          summary: errorMessage,
          error: true
        };
      }
    });

    const memberResults = await Promise.all(memberPromises);
    
    // Generate chairman summary
    let chairmanSummary = "Council analysis complete.";
    try {
      const chairmanParams = {
        model: chairmanModel,
        messages: [
          {
            role: 'system',
            content: 'You are the Council Chairman. Synthesize the council members\' analyses into a cohesive summary with key insights and recommendations.'
          },
          {
            role: 'user',
            content: `Question: ${question}\n\nCouncil Members' Responses:\n${memberResults.map(m => `${m.name}: ${m.summary}`).join('\n\n')}\n\nProvide a synthesis:`
          }
        ],
        temperature: usesCompletionTokens(chairmanModel) ? 1 : 0.5
      };
      
      if (usesCompletionTokens(chairmanModel)) {
        chairmanParams.max_completion_tokens = 300;
      } else {
        chairmanParams.max_tokens = 300;
      }
      
      const summaryCompletion = await client.chat.completions.create(chairmanParams);
      chairmanSummary = summaryCompletion.choices[0].message.content;
    } catch (error) {
      context.log('Error generating chairman summary', error);
      chairmanSummary = "Unable to generate chairman summary. Please review individual member responses.";
    }

    const responseData = {
      question,
      members: memberResults,
      chairman: {
        id: chairmanModel,
        name: `${chairmanModel.toUpperCase()} (Chairman)`,
        provider: 'Azure OpenAI',
        color: getModelColor(chairmanModel),
        summary: chairmanSummary
      },
      timestamp: new Date().toISOString(),
      mode: 'live'
    };

    context.res = {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type'
      },
      body: {
        success: true,
        mode: 'live',
        question,
        data: responseData
      }
    };

  } catch (error) {
    context.log.error('Council endpoint error:', error);
    context.res = {
      status: 500,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
      },
      body: { error: 'Internal server error', message: error.message }
    };
  }
}