import OpenAI from 'openai';

// Mock responses for testing without API keys
const getMockCouncilResponse = (question, members) => {
  const mockMembers = members.map((member, index) => ({
    id: member.id,
    name: member.name,
    provider: member.provider,
    color: member.color,
    summary: `Mock response from ${member.name}: This is a simulated analysis for "${question.substring(0, 50)}...".`,
    reasoning: `## Analysis by ${member.name}\n\n- **Key Point 1**: Simulated insight from Azure OpenAI\n- **Key Point 2**: Mock reasoning for demonstration\n- **Conclusion**: This is a test response in mock mode.\n\n*Generated by: ${member.provider}*`,
    confidence: 75 + (index * 5)
  }));

  return {
    question,
    members: mockMembers,
    chairman: {
      finalDecision: `## Chairman's Decision\n\nAfter reviewing all council member responses, here's the synthesized recommendation:\n\n**Consensus Points:**\n- All members agree this is a mock demonstration\n- Azure migration is proceeding successfully\n- Frontend deployment is working correctly\n\n**Final Recommendation:**\nThis mock response demonstrates that the Azure Static Web Apps deployment is functioning properly. The council framework is ready for real AI integration once Azure OpenAI credentials are configured.\n\n*Chairman Model: GPT-5.1 (Mock Mode)*`,
      consensusScore: 85,
      keyAgreements: ['Mock demonstration working', 'Azure deployment successful', 'Frontend integration complete'],
      keyDisagreements: ['No real disagreements in mock mode']
    }
  };
};

const getOpenAIClient = () => {
  const apiKey = process.env.AZURE_OPENAI_API_KEY || process.env.AI_INTEGRATIONS_OPENAI_API_KEY;
  const baseURL = process.env.AZURE_OPENAI_ENDPOINT || process.env.AI_INTEGRATIONS_OPENAI_BASE_URL;

  if (!apiKey || !baseURL) {
    return null;
  }

  return new OpenAI({
    apiKey,
    baseURL
  });
};

module.exports = async function (context, req) {
  context.log('Council endpoint called');

  // For development, hardcode USE_MOCK to true
  // TODO: Make this configurable via environment variables later
  const useMock = process.env.USE_MOCK === 'true' || true; // Always use mock for now
  const { question, selectedMemberIds = ['gpt-5.1', 'gpt-4o', 'o3'], chairmanModelId = 'gpt-5.1' } = req.body || {};

  if (!question) {
    context.res = {
      status: 400,
      body: { error: 'Question is required' }
    };
    return;
  }

  try {
    // Mock mode or no API keys - return simulated response
    if (useMock || !getOpenAIClient()) {
      const mockMembers = selectedMemberIds.map(id => ({
        id,
        name: id.toUpperCase(),
        provider: 'Azure OpenAI',
        color: '#10B981'
      }));

      const response = getMockCouncilResponse(question, mockMembers);
      
      context.res = {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*'
        },
        body: response
      };
      return;
    }

    // Real API implementation would go here
    // For now, return mock response
    context.res = {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
      },
      body: { message: 'Real Azure OpenAI integration coming in Phase 3' }
    };

  } catch (error) {
    context.log.error('Council endpoint error:', error);
    context.res = {
      status: 500,
      body: { error: 'Internal server error' }
    };
  }
}